// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApYtPmJHisfT7XFySnlZSa3rQbZkapzZc',
    appId: '1:471044439807:web:387041aaf2ca28b1a8d6ca',
    messagingSenderId: '471044439807',
    projectId: 'crud1-operation',
    authDomain: 'crud1-operation.firebaseapp.com',
    storageBucket: 'crud1-operation.appspot.com',
    measurementId: 'G-67EZM719L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD343knGZSRTLefoWvT44PDZ76qpNVig_k',
    appId: '1:471044439807:android:15b0934b6e1f01a3a8d6ca',
    messagingSenderId: '471044439807',
    projectId: 'crud1-operation',
    storageBucket: 'crud1-operation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIlw0K6KtH3zz9aNvIatsRolG4LEy9jr4',
    appId: '1:471044439807:ios:19042717c4719e83a8d6ca',
    messagingSenderId: '471044439807',
    projectId: 'crud1-operation',
    storageBucket: 'crud1-operation.appspot.com',
    iosBundleId: 'com.example.crudOperations',
  );
}
